version: "3.9"


services:
  api:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8080
    container_name: notebook-api
    ports:
      - "8080:8080"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.base
      - POSTGRES_HOST=db
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    container_name: notebook-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespass
    volumes:
      - ./postgres-data/db:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: notebook-redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_DB=0
      - REDIS_CACHE_DB=1 
    volumes:
      - ./redis-data:/var/lib/redis/data

  worker:
    container_name: notebook-worker
    build: .
    command: python3 manage.py rqworker default
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.base
      - POSTGRES_HOST=db
    depends_on:
      - redis
      - db

  scheduler:
    build: .
    container_name: notebook-scheduler
    command: python3 manage.py agenda_atualizacao
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.base
      - POSTGRES_HOST=db
    depends_on:
      - redis
      - db

volumes:
  db:
  redis:
