version: "3.9"


services:
  api:
    build: .
    command: gunicorn core.wsgi --bind 0.0.0.0:8000 --access-logfile "gunicorn.log" --log-level "debug" --max-requests "50" --workers "2"
    container_name: notebook-api
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_DB=0
      - REDIS_CACHE_DB=1 
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    container_name: notebook-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data/db:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: notebook-redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_DB=0
      - REDIS_CACHE_DB=1 
    volumes:
      - ./redis-data:/var/lib/redis/data

  worker:
    container_name: notebook-worker
    build: .
    command: python3 manage.py rqworker default
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_DB=0
      - REDIS_CACHE_DB=1 
    depends_on:
      - redis
      - db

  scheduler:
    build: .
    container_name: notebook-scheduler
    command: python3 manage.py agenda_atualizacao
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_DB=0
      - REDIS_CACHE_DB=1 
    depends_on:
      - redis
      - db

volumes:
  db:
  redis:
